name: "Check Specifications CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Install dependencies
        run: nix develop
      - name: Run TLC on all specifications
        run: |
          find . -name "*.tla" | while read spec; do
            echo "Checking specification: $spec"
            dir=$(dirname "$spec")
            filename=$(basename "$spec")
            module="${filename%.*}"
            cfg="${module}.cfg"
            output_file=".github/tlc_output/${dir}_${module}_output.log"

            if [ -f "$dir/$cfg" ]; then
              nix develop --command tlc -config "$dir/$cfg" "$spec" > "$output_file" 2>&1
              echo "Output saved to $output_file"
            else
              echo "Warning: No config file found for $spec. Skipping." | tee "$output_file"
            fi
          done
      - name: Check for TLC errors
        run: |
          if grep -r "Error:" .github/tlc_output/; then
            echo "TLC found errors in one or more specifications."
            exit 1
          else
            echo "All specifications checked successfully."
          fi
      - name: Upload TLC output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlc-output
          path: .github/tlc_output
        if: always()
