name: "Check Specifications CI"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - name: Install dependencies
        run: nix develop
      - name: Run TLC on all specifications
        run: |
          find . -name "*.tla" | while read spec; do
            echo "Checking specification: $spec"
            dir=$(dirname "$spec")
            filename=$(basename "$spec")
            module="${filename%.*}"
            cfg="${module}.cfg"

            if [ -f "$dir/$cfg" ]; then
              nix develop --command tlc -config "$dir/$cfg" "$spec"
            else
              echo "Warning: No config file found for $spec. Skipping."
            fi
          done
      - name: Check for TLC errors
        run: |
          if grep -r "Error:" .; then
            echo "TLC found errors in one or more specifications."
            exit 1
          else
            echo "All specifications checked successfully."
          fi
